from __future__ import annotations

import json
import os
import time
import winreg
from typing import Any

import aiohttp

from app.services.software_index import find_software
from app.services.tool_registry import tool_registry

ELECTRON_TOOL_URL = "http://127.0.0.1:9000/execute"

SCHEMA_TO_EXECUTOR_MAP = {
    "open": "app:launch",
    "shell": "system:command",
    "systemControl": "system:command",
    "searchFiles": "file:search",
    "getSystemInfo": "system:info",
    "diskCleanup": "disk:cleanup",
    "tempScan": "temp:scan",
}

SYSTEM_CONTROL_COMMANDS = {
    "volume_up": "powershell -Command \"$obj = New-Object -ComObject WScript.Shell; $obj.SendKeys([char]175)\"",
    "volume_down": "powershell -Command \"$obj = New-Object -ComObject WScript.Shell; $obj.SendKeys([char]174)\"",
    "mute": "powershell -Command \"$obj = New-Object -ComObject WScript.Shell; $obj.SendKeys([char]173)\"",
    "shutdown": "shutdown /s /t 60",
    "sleep": "powershell -Command \"Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Application]::SetSuspendState('Suspend', $false, $false)\"",
    "brightness_up": "powershell -Command \"(Get-WmiObject -Namespace root/WMI -Class WmiMonitorBrightnessMethods).WmiSetBrightness(1, [Math]::Min(100, (Get-WmiObject -Namespace root/WMI -Class WmiMonitorBrightness).CurrentBrightness + 10))\"",
    "brightness_down": "powershell -Command \"(Get-WmiObject -Namespace root/WMI -Class WmiMonitorBrightnessMethods).WmiSetBrightness(1, [Math]::Max(0, (Get-WmiObject -Namespace root/WMI -Class WmiMonitorBrightness).CurrentBrightness - 10))\"",
}


def _get_template_content(template_name: str, file_path: str) -> str:
    """根据模板名和文件路径返回基础模板内容"""
    if template_name == "modern_login" or file_path.endswith(".html"):
        return """<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { min-height: 100vh; display: flex; align-items: center; justify-content: center; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
        .login-card { background: rgba(255,255,255,0.95); border-radius: 16px; padding: 40px; width: 400px; box-shadow: 0 20px 60px rgba(0,0,0,0.3); }
        .login-card h1 { text-align: center; color: #333; margin-bottom: 30px; font-size: 24px; }
        .form-group { margin-bottom: 20px; }
        .form-group label { display: block; color: #555; margin-bottom: 6px; font-size: 14px; }
        .form-group input { width: 100%; padding: 12px 16px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 15px; transition: border-color 0.3s; }
        .form-group input:focus { outline: none; border-color: #667eea; }
        .btn-login { width: 100%; padding: 14px; background: linear-gradient(135deg, #667eea, #764ba2); color: #fff; border: none; border-radius: 8px; font-size: 16px; cursor: pointer; transition: transform 0.2s; }
        .btn-login:hover { transform: translateY(-2px); }
        .footer { text-align: center; margin-top: 20px; color: #888; font-size: 13px; }
    </style>
</head>
<body>
    <div class="login-card">
        <h1>Welcome Back</h1>
        <div class="form-group">
            <label>Email</label>
            <input type="email" placeholder="your@email.com">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" placeholder="Enter password">
        </div>
        <button class="btn-login">Sign In</button>
        <div class="footer">Don't have an account? <a href="#" style="color:#667eea;">Sign Up</a></div>
    </div>
</body>
</html>"""
    
    if file_path.endswith(".py"):
        return f'''# Generated by AI Desktop Agent
# File: {file_path}

def main():
    print("Hello from AI Desktop Agent!")

if __name__ == "__main__":
    main()
'''
    
    if file_path.endswith(".js") or file_path.endswith(".ts"):
        return f'''// Generated by AI Desktop Agent
// File: {file_path}

function main() {{
    console.log("Hello from AI Desktop Agent!");
}}

main();
'''
    
    return f"// Generated by AI Desktop Agent\n// Template: {template_name}\n// File: {file_path}\n"

# ===== 执行器级路径查找与失败记录（避免跨层循环依赖）=====

def _find_app_path(name: str) -> str | None:
    """根据应用名查找 Windows 绝对路径（使用软件索引，支持模糊匹配）"""
    # 优先使用软件索引（支持模糊匹配、别名、系统内置工具）
    entry = find_software(name)
    if entry and entry.exe_path and os.path.exists(entry.exe_path):
        return entry.exe_path
    
    # 兜底：传统注册表 App Paths 查找
    exe_name = name if name.endswith('.exe') else f"{name}.exe"
    
    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE,
                          r"SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths") as key:
            try:
                with winreg.OpenKey(key, exe_name) as app_key:
                    path, _ = winreg.QueryValueEx(app_key, None)
                    if path and os.path.exists(path):
                        return path
            except FileNotFoundError:
                pass
    except Exception:
        pass
    
    return None


def _resolve_launch_path(args: dict[str, Any]) -> dict[str, Any]:
    """对 app:launch 参数进行路径解析，返回新的 args"""
    path = args.get("path", "")
    if not path:
        return args
    
    # 已经是绝对路径且存在 -> 直接放行
    if os.path.isabs(path) and os.path.exists(path):
        return args
    
    # 相对路径/文件名 -> 使用软件索引查找绝对路径
    if not os.path.isabs(path):
        found = _find_app_path(path)
        if found:
            new_args = dict(args)
            new_args["path"] = found
            return new_args
    
    # 绝对路径但文件不存在 -> 尝试按文件名重新查找
    if os.path.isabs(path) and not os.path.exists(path):
        found = _find_app_path(os.path.basename(path))
        if found:
            new_args = dict(args)
            new_args["path"] = found
            return new_args
    
    return args


def _record_executor_failure(tool: str, params: dict[str, Any], reason: str):
    """记录执行失败到日志（供排查）"""
    # 打印到后端日志，Electron 控制台也能看到
    print(f"[Executor] 执行失败记录 [{tool}]: {reason} | params={json.dumps(params, ensure_ascii=False)}")


async def execute_tool_calls(tool_calls: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """
    执行 LLM 要求的工具调用，返回 tool 消息列表（供第二轮 LLM 使用）
    """
    results: list[dict[str, Any]] = []
    for call in tool_calls:
        name = call["function"]["name"]
        try:
            args = json.loads(call["function"]["arguments"])
        except (json.JSONDecodeError, KeyError):
            args = {}

        result = await _execute_single_tool(name, args)
        results.append({
            "tool_call_id": call["id"],
            "role": "tool",
            "content": json.dumps(result, ensure_ascii=False),
        })
    return results


async def _execute_single_tool(name: str, args: dict[str, Any]) -> dict[str, Any]:
    # ===== 0. Schema名称 → ActionExecutor名称 映射 =====
    original_name = name
    if name in SCHEMA_TO_EXECUTOR_MAP:
        name = SCHEMA_TO_EXECUTOR_MAP[name]
    if original_name == "open":
        args = {"path": args.get("target", ""), **{k: v for k, v in args.items() if k != "target"}}
    if original_name == "shell":
        cmd = args.get("command", "")
        cmd_args = args.get("args", [])
        args = {"command": cmd, "args": cmd_args}
    if original_name == "systemControl":
        action = args.get("action", "")
        if action in SYSTEM_CONTROL_COMMANDS:
            args = {"command": SYSTEM_CONTROL_COMMANDS[action]}
        else:
            return {"ok": False, "error": f"Unknown systemControl action: {action}"}
    if original_name == "searchFiles":
        args = {"path": args.get("dir", ""), "pattern": args.get("keyword", "*")}
    if original_name == "diskCleanup":
        args = {"max": args.get("max", 50)}
    if original_name == "tempScan":
        args = {"max": args.get("max", 50)}

    # ===== 0a. ide:launch 执行前参数预处理 =====
    if name == "ide:launch":
        ide = args.get("ide", "vscode")
        if ide == "vscode":
            args.setdefault("path", "Code.exe")
        elif ide == "cursor":
            args.setdefault("path", "Cursor.exe")
        
        if args.get("action") == "create_project" and args.get("files"):
            import os
            project_name = args.get("project_name", "untitled")
            base_dir = os.path.expanduser("~/Documents/AI_Generated")
            project_dir = os.path.join(base_dir, project_name)
            os.makedirs(project_dir, exist_ok=True)
            
            for file_spec in args["files"]:
                file_path = os.path.join(project_dir, file_spec.get("path", "index.html"))
                file_dir = os.path.dirname(file_path)
                if file_dir:
                    os.makedirs(file_dir, exist_ok=True)
                
                template_name = file_spec.get("template", "")
                content = _get_template_content(template_name, file_spec.get("path", ""))
                
                try:
                    with open(file_path, "w", encoding="utf-8") as f:
                        f.write(content)
                except Exception as e:
                    print(f"[Executor] 写入模板文件失败: {file_path}, err={e}")
            
            args["project_path"] = project_dir
            args["args"] = [project_dir]
            
            if args.get("auto_preview"):
                index_file = os.path.join(project_dir, "index.html")
                if os.path.exists(index_file):
                    args["preview_url"] = f"file:///{index_file.replace(os.sep, '/')}"

    # ===== 0b. app:launch 执行前路径解析（最后一道防线）=====
    if name == "app:launch":
        original_path = args.get("path", "")
        args = _resolve_launch_path(args)
        resolved_path = args.get("path", "")
        
        # 如果解析后仍无效，直接拦截，不发给 Electron
        if not resolved_path or not os.path.isabs(resolved_path):
            _record_executor_failure(name, {"path": original_path}, "无法解析为有效绝对路径")
            return {
                "ok": False,
                "error": f"找不到应用 {original_path}，请提供完整路径 (VALIDATION_SKIPPED)",
                "code": "PATH_NOT_FOUND"
            }
        
        # 如果路径被修改了，打印日志
        if resolved_path != original_path:
            print(f"[Executor] 路径自动解析: {original_path} -> {resolved_path}")

    # 0c. browser:search 参数预处理
    if name == "browser:search":
        query = args.get("query", "")
        if not query:
            return {"ok": False, "error": "browser:search 需要 query 参数"}
        import urllib.parse
        is_chinese = any('\u4e00' <= c <= '\u9fff' for c in query)
        search_url = f"https://www.baidu.com/s?wd={urllib.parse.quote(query)}" if is_chinese else f"https://www.google.com/search?q={urllib.parse.quote(query)}"
        browser = args.get("browser", "edge")
        browser_exe = "chrome.exe" if browser == "chrome" else "msedge.exe"
        args = {"path": browser_exe, "url": search_url}
        name = "app:launch"

    # 0d. keyboard:type 参数预处理
    if name == "keyboard:type":
        text = args.get("text", "")
        if not text:
            return {"ok": False, "error": "keyboard:type 需要 text 参数"}

    # 1. requires_confirmation 拦截：高危工具需用户确认
    tool_def = tool_registry.get_tool(name)
    if tool_def and tool_def.requires_confirmation:
        return {
            "ok": False,
            "confirm_required": True,
            "action": name,
            "message": f"工具 {name} 需要用户确认后才能执行（risk={tool_def.risk}）",
        }

    # 2. 进程黑名单校验：禁止结束系统关键进程
    PROTECTED_PROCESS_NAMES = {
        "system", "idle", "registry", "smss.exe", "csrss.exe", "wininit.exe",
        "winlogon.exe", "services.exe", "lsass.exe", "svchost.exe", "explorer.exe",
        "electron.exe", "dwm.exe",
    }
    if name == "process:kill":
        kill_name = str(args.get("name", "")).strip().lower()
        if kill_name in PROTECTED_PROCESS_NAMES:
            return {"ok": False, "error": f"进程 {kill_name} 是系统关键进程，禁止结束", "blocked": True}

    # 3. 危险命令拦截
    if name == "shell":
        cmd = args.get("command", "")
        blacklist = ["rm -rf /", "format", "del /f /s /q c:\\", "rd /s /q c:", "mkfs"]
        if any(b in cmd.lower() for b in blacklist):
            return {"ok": False, "error": "危险命令被拦截", "blocked": True}

    # 2. 需确认操作（不直接执行，返回确认请求）
    if name == "systemControl" and args.get("action") in ("shutdown", "sleep"):
        return {
            "ok": False,
            "confirm_required": True,
            "action": args["action"],
            "message": f"即将执行 {args['action']}，请确认是否继续？",
        }

    # 3. 调 Electron 主进程执行
    result: dict[str, Any]
    try:
        timeout = aiohttp.ClientTimeout(total=30)
        async with aiohttp.ClientSession() as session:
            async with session.post(
                ELECTRON_TOOL_URL,
                json={"tool": name, "params": args},
                timeout=timeout,
            ) as resp:
                if resp.status == 200:
                    result = await resp.json()
                else:
                    text = await resp.text()
                    result = {
                        "ok": False,
                        "error": f"桌面执行器返回错误: HTTP {resp.status}",
                        "detail": text[:200],
                    }
    except aiohttp.ClientConnectorError:
        result = {
            "ok": False,
            "error": "无法连接桌面执行器（Electron 主进程未启动？）",
            "note": "请确保 Electron 主进程已启动并监听 127.0.0.1:9000",
        }
    except Exception as e:
        result = {"ok": False, "error": f"执行异常: {str(e)}"}

    # ===== 4. 执行后失败记录（Electron 返回错误时记录）=====
    if not result.get("ok", True):
        _record_executor_failure(name, args, result.get("error", "unknown"))
        
        # 如果是 app:launch 且 Electron 也报找不到，确保返回统一格式
        if name == "app:launch" and "找不到" in result.get("error", ""):
            result["code"] = "PATH_NOT_FOUND"

    return result